# Generated by Django 3.0.7 on 2020-07-02 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabellaSettori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settore', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TabellaTurni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('orario_turno', models.CharField(max_length=30)),
                ('numero_posti_disponibili', models.PositiveIntegerField()),
                ('settore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settori', to='prenotazioni.TabellaSettori')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('data_prenotazione', models.DateField()),
                ('numero_accompagnatori', models.PositiveIntegerField(default=2)),
                ('numero_totale_alunni', models.PositiveIntegerField()),
                ('esigenze', models.CharField(max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentiPrenotazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('classe', models.CharField(max_length=30)),
                ('numero_alunni', models.PositiveIntegerField()),
                ('prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_prenotazione', to='prenotazioni.Prenotazione')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turni', to='prenotazioni.TabellaTurni')),
            ],
        ),
    ]
