# Generated by Django 3.0.7 on 2020-07-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentiprenotazione',
            options={'verbose_name': 'Dettaglio Prenotazione', 'verbose_name_plural': 'Dettaglio Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name': 'Prenotazione', 'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='tabellasettori',
            options={'verbose_name': 'Settore', 'verbose_name_plural': 'Settori'},
        ),
        migrations.AlterModelOptions(
            name='tabellaturni',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turni'},
        ),
        migrations.AlterField(
            model_name='movimentiprenotazione',
            name='classe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movimentiprenotazione',
            name='numero_alunni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='esigenze',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='tabellasettori',
            name='settore',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tabellaturni',
            name='numero_posti_disponibili',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
