# Generated by Django 3.0.7 on 2020-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0002_auto_20200702_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='esigenze',
            field=models.TextField(blank=True, null=True),
        ),
    ]
