# Generated by Django 3.0.7 on 2020-07-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_auto_20200702_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentiprenotazione',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turni', to='prenotazioni.TabellaTurni'),
        ),
    ]
