# Generated by Django 3.0.7 on 2020-08-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0005_anagraficascuole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anagraficascuole',
            old_name='nome',
            new_name='nome_scuola',
        ),
        migrations.AddField(
            model_name='movimentiprenotazione',
            name='nome_scuola',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
