# Generated by Django 3.0.7 on 2020-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0007_auto_20200823_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='Scuola',
            field=models.BooleanField(null=True),
        ),
    ]
