# Generated by Django 3.0.7 on 2020-08-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0008_prenotazione_scuola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazione',
            old_name='Scuola',
            new_name='scuola',
        ),
    ]
