# Generated by Django 3.0.7 on 2020-09-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0009_auto_20200824_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='status',
            field=models.BooleanField(choices=[('0', 'Da confermare'), ('1', 'Confermato')], null=True),
        ),
    ]
