# Generated by Django 3.0.7 on 2020-09-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0010_prenotazione_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='status',
            field=models.CharField(choices=[('UN', 'Unpublished'), ('PB', 'Published')], default='UN', max_length=2, null=True),
        ),
    ]
