# Generated by Django 3.0.7 on 2020-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0012_auto_20200909_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='status',
            field=models.CharField(choices=[('DC', 'Da Confermare'), ('CO', 'Confermato'), ("<class 'prenotazioni.models.StatusPrenotazione.Meta'>", 'Meta')], default='DC', max_length=60, null=True),
        ),
    ]
