# Generated by Django 3.0.7 on 2020-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0015_tabellaruoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficascuole',
            name='sigla',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
