# Generated by Django 3.0.7 on 2020-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0016_anagraficascuole_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='pagato',
            field=models.BooleanField(default=False),
        ),
    ]
