# Generated by Django 3.0.7 on 2020-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0017_prenotazione_pagato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='pagato',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='scuola',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
