# Generated by Django 3.0.7 on 2020-09-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0019_auto_20200924_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='nome_scuola',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
