# Generated by Django 3.0.7 on 2020-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0021_auto_20200924_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='numero_totale_alunni',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
