# Generated by Django 3.0.7 on 2020-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0022_auto_20200924_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagraficascuole',
            options={'verbose_name': 'scuola', 'verbose_name_plural': 'scuole'},
        ),
        migrations.AlterField(
            model_name='movimentiprenotazione',
            name='numero_alunni',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='numero_accompagnatori',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='numero_totale_alunni',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
