# Generated by Django 3.0.7 on 2020-10-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0023_auto_20201023_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='numero_totale_alunni',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
