# Generated by Django 3.0.7 on 2021-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0024_auto_20201023_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabellaaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'ruolo',
                'verbose_name_plural': 'ruoli',
            },
        ),
    ]
