# Generated by Django 3.0.7 on 2021-01-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0025_tabellaaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(blank=True, max_length=250)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('collegamento', models.CharField(blank=True, max_length=128)),
                ('settore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settorivideo', to='prenotazioni.TabellaSettori')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
        migrations.DeleteModel(
            name='Tabellaaa',
        ),
    ]
