# Generated by Django 3.0.7 on 2021-01-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0026_auto_20210111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficavideo',
            name='titolo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimentiprenotazione',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='prenotazioni.AnagraficaVideo'),
        ),
    ]
