# Generated by Django 3.0.7 on 2021-01-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0027_auto_20210112_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentiprenotazione',
            name='video',
        ),
    ]
