# Generated by Django 3.0.7 on 2021-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0028_remove_movimentiprenotazione_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='argomentiPreferiti',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='mailConfermaInviata',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='mailInformativaInviata',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='tipoVisita',
            field=models.CharField(choices=[('VI', 'Virtuale'), ('PR', 'In Presenza')], default='VI', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='status',
            field=models.CharField(choices=[('DC', 'Da Confermare'), ('CO', 'Confermato'), ('EF', 'Effettuata')], default='DC', max_length=2, null=True),
        ),
    ]
