# Generated by Django 3.0.7 on 2021-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0031_auto_20210202_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='nome_scuola',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
