# Generated by Django 3.0.7 on 2022-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0034_auto_20210207_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentiprenotazione',
            name='orario_turno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
