# Generated by Django 3.0.7 on 2022-01-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0035_movimentiprenotazione_orario_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentiprenotazione',
            name='settore',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
