# Generated by Django 3.0.7 on 2022-01-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0036_movimentiprenotazione_settore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentiprenotazione',
            name='settore',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
