# Generated by Django 3.0.7 on 2022-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0041_auto_20220122_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentiprenotazione',
            name='orario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
