# Generated by Django 3.0.7 on 2020-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ruolo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
