# Generated by Django 3.0.7 on 2021-02-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_ruolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isguida',
            field=models.BooleanField(default=False),
        ),
    ]
